version: '2'

#letsencrypt server (nginx)

services:
  letsencrypt:
    image: linuxserver/swag
#    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - URL=csgb.f5.si
      - SUBDOMAINS=moudame, contents, event
      - VALIDATION=http
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    links:
      - wordpress-moudame
      - wordpress-ggp
#      - wordpress
    volumes:
      - letsencrypt-config:/config

############# 共用データベース ################

  wordpress-mariadb:
    image: mariadb
    volumes:
      - wordpress-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

############# コミュ研beta ################

#  wordpress:
#    image: wordpress:latest
#    ports:
#      - "8080:80"
#    links:
#      - wordpress-mariadb
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: wordpress-mariadb
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#    volumes:
#      - wordpress-files:/var/www/html

############# もうだめ君ファンサイト ################

  wordpress-moudame:
    image: wordpress:latest
    ports:
      - "28080:80"
    links:
      - wordpress-mariadb
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-mariadb
      WORDPRESS_DB_USER: wordpress_moudame
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_moudame
    volumes:
      - wordpress-files-moudame:/var/www/html


############# Green Grobe Partners ################

#  wordpress-mariadb-ggp:
#    image: mariadb
#    volumes:
#      - wordpress-db-ggp:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: wordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress

  wordpress-ggp:
    image: wordpress:latest
    ports:
      - "18080:80"
    links:
      - wordpress-mariadb
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-mariadb
      WORDPRESS_DB_USER: wordpress_ggp
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_ggp
    volumes:
      - wordpress-files-ggp:/var/www/html


volumes:
  wordpress-files:
    external: true
  wordpress-db:
    external: true
  letsencrypt-config:
    external: true
  wordpress-files-ggp:
    external: true
#  wordpress-db-ggp:
#    external: true
  wordpress-files-moudame:
    external: true

