version: '2'

#letsencrypt server (nginx)

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - URL=csgb.f5.si
      - SUBDOMAINS=contents, event
      - VALIDATION=http
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    links:
      - wordpress
    volumes:
      - letsencrypt-config:/config

############# コミュ研beta ################
  wordpress-mariadb:
    image: mariadb
    volumes:
      - wordpress-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    links:
      - wordpress-mariadb
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-files:/var/www/html

############# Green Grobe Partners ################
  wordpress-mariadb-ggp:
    image: mariadb
    volumes:
      - wordpress-db-ggp:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress-ggp:
    image: wordpress:latest
    ports:
      - "18080:80"
    links:
      - wordpress-mariadb
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-mariadb-ggp
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress-files-ggp:/var/www/html

############# Lemonade Kids ################
#  wordpress-mariadb-lemokids:
#    image: mariadb
#    volumes:
#      - wordpress-db-lemokids:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: wordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
#
#  wordpress-lemokids:
#    image: wordpress:latest
#    ports:
#      - "28080:80"
#    links:
#      - wordpress-mariadb-lemokids
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: wordpress-mariadb-lemokids
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#    volumes:
#      - wordpress-files-lemokids:/var/www/html

volumes:
  wordpress-files:
    external: true
  wordpress-db:
    external: true
  letsencrypt-config:
    external: true
  wordpress-files-ggp:
    external: true
  wordpress-db-ggp:
    external: true
#  wordpress-files-lemokids:
#    external: true
#  wordpress-db-lemokids:
#    external: true

